#!/bin/bash
#SBATCH --partition=defq
#SBATCH --nodes=1
#SBATCH --tasks=1
#SBATCH --cpus-per-task=80
#SBATCH --time=24:00:00
#SBATCH -J notebook
#SBATCH --output=./out/slurm-%j.out
###SBATCH --mail-user=dpirvu@perimeterinstitute.ca

cd '/home/dpirvu/project/paper_prefactor/'

jupyter nbconvert --execute average.ipynb --to 'html' --ExecutePreprocessor.timeout=-1
#jupyter nbconvert --execute deboost.ipynb --to 'html' --ExecutePreprocessor.timeout=-1
#jupyter nbconvert --execute convergence_tests.ipynb --to 'html' --ExecutePreprocessor.timeout=-1
